### ISSUE TITLE
Ao tentar rodar a aplicação no meu android recebo este erro

### ISSUE THREAD

**Issue by HeckMarques** [fabricadecodigo/ionicfirebaseauth#1]
BUILD FAILED in 54s
(node:7224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by feliperfranco** [comment]
Use as mesmas versões do angular e firebase que estão no https://github.com/fabricadecodigo/ionicfirebaseauth/blob/master/package.json
As versões mais novas costumam não se mais compatíveis.
Valeu!
